FROM rust:1.69 as builder
WORKDIR app
RUN rustup update
COPY . .
RUN cargo build --release

FROM gcr.io/distroless/cc as runtime
COPY --from=builder /app/target/release/evalrs /
COPY --from=builder /app/config /config
ENTRYPOINT ["./evalrs"]
